on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: insuranceregistry.azurecr.io
        username: ${{ secrets.acr_insuranceregistry_username }}
        password: ${{ secrets.acr_insuranceregistry_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/backend-mapv1" -f  "backend-mapv1/Dockerfile" -t insuranceregistry.azurecr.io/insurancekuber:${{ github.sha }}
        docker push insuranceregistry.azurecr.io/insurancekuber:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_insurancekuber_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep insurance-dev | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace insurance-dev`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: insurance-dev
        container-registry-url: insuranceregistry.azurecr.io
        container-registry-username: ${{ secrets.acr_insuranceregistry_username }}
        container-registry-password: ${{ secrets.acr_insuranceregistry_password }}
        secret-name: insurancekubdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: insurance-dev
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          insuranceregistry.azurecr.io/insurancekuber:${{ github.sha }}
        imagepullsecrets: |
          insurancekubdockerauth